#
#server:
# port: 8080
#
#spring:
# datasource:
#  url: jdbc:mysql://localhost:3306/bulk_reconciliation
#  username: root
#  password: Bir@tn@g@r1
#  driver-class-name: com.mysql.cj.jdbc.Driver
#  servlet:
#   multipart: max-file-size:3MB
#              max-request-size=3MB
#
#jpa:
# properties:
#  hibernate:
#   dialect: org.hibernate.dialect.MySQL8InnoDBDialect
#   format-sql: true
# hibernate:
#  ddl-auto: create
#
# show-sql: true
#jackson:
# serialization:
#  fail-on-empty-beans: false